java.lang.IllegalStateException: Cannot call sendError() after the response has been committed (#67)
* add module

* add module: chat

* add module: chat

* add scheduler

* oauth2

* Schedule

* add module: scheduler

* scheduler: rename path

* scheduler: rename path core

* merge

* redis startup.sh shutdown.sh

* Merge remote-tracking branch 'upstream/master'

Conflicts:
	alpha-scheduler/alpha-scheduler-api/src/main/java/com/geektcp/alpha/scheduler/api/controller/JobCodeController.java

* 经测试，@Transactional注解放在控制器，非接口实现的类也是有效的。
加了注解后，要等所有代码跑完才集中执行sql，@Transactional实现了事务的作用。

* config

* package commit

* config filter

* can not login but filter passed

* can not login but filter passed

* review

* provider

* java.lang.IllegalStateException: Cannot call sendError() after the response has been committed

Co-authored-by: thy_shenzhen <thy_shenzhen@163.com>
Co-authored-by: haiyang <geektcp@163.com>